dbc/dbc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
]

dbc/home/urls.py
from . import views
from django.urls import path

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('locations/', views.locations, name='locations'),
    path('forms/', views.forms, name='forms'),
    path('learn/', views.learn, name='learn'),
]

dbc/home/models.py
from django.db import models

# Create your models here.

dbc/home/views.py
from django.shortcuts import render
from django.views import View
from django.http import FileResponse, Http404, HttpResponse

# Create your views here
def index(request):
    return render(request, 'home/index.html')

def about(request):
    return render(request, 'home/about.html')

def services(request):
    return render(request, 'home/services.html')

def locations(request):
    return render(request, 'home/locations.html')

def forms(request):
    return render(request, 'home/forms.html')

def learn(request):
    return render(request, 'home/learn.html')

dbc/home/templates/base.html
<!DOCTYPE html> {% load staticfiles %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
        {% include 'css.html' %}
    <title>Doug Borrmann Counseling</title>
</head>

<body>
        {% include 'navbar.html' %}
        
    {% block content %}  
    {% endblock %}
</body>
    {% include 'footer.html' %}
</html>

dbc/home/templates/css.html
{% load static %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/styles.css' %}">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

dbc/home/templates/footer.html
<!-- Footer -->
<footer class="page-footer font-small">

    <!-- Footer Text -->
    <div class="container-fluid text-center text-md-left">

        <!-- Grid row -->
        <div class="row">

            <!-- Grid column -->
            <div class="col-md-6 mt-md-0 mt-3">

                <!-- Content -->
                <h3 class="text-uppercase font-weight-bold text-center">Contact</h3>

                <br>
                <div class="text-center">
                    <a class="lead a-footer" href="mailto:doug@dougborrman.com">doug@dougborrman.com</a><br>
                    <a class="lead a-footer" href="tel:+1-480-258-9113">Tel: 480.258.9113</a>
                </div>
            </div>
            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none pb-3">

            <!-- Grid column -->
            <div class="col-md-6 mb-md-0 mb-3">

                <!-- Content -->
                <h3 class="text-uppercase font-weight-bold text-center">Connect</h3>

                <br>
                <div class='text-center'>
                    <a href="#" class="fa fa-facebook"></a>
                    <a href="#" class="fa fa-twitter"></a>
                    <a href="#" class="fa fa-google"></a>
                    <a href="#" class="fa fa-linkedin"></a>
                </div>

            </div>
            <!-- Grid column -->

        </div>
        <!-- Grid row -->

    </div>
    <!-- Footer Text -->



</footer>
<!-- Footer -->

dbc/home/templates/home/about.html
{% extends 'base.html' %} {% block content %}



<div class="padding">
  <div class="container">
    <div class="row">
      <div class="col-lg-3">
        <img class="card-img-top" src="/static/assets/db.jpg" alt="Card image cap">
      </div>
      <div class="col-lg-9">
        <h2 class="card-title">Doug Borrmann</h2>
        <h5 class="card-title">M.S., Licensed Associate Counselor (LAC)</h5>
        <br>

        <p class="lead">Doug received his Master’s degree in Professional Counseling from Grand Canyon University in 2017. Prior to his entrance
          into the world of mental health, he obtained his Bachelor’s degree in Music from Arizona State University and embarked
          on a fourteen-year career as a professional musician. He served as the director of music for several large churches
          and has been involved in ministry for the majority of his life. He feels this time serves his counseling career
          well because he worked with a wide variety of people from many different backgrounds.</p>

        <p class="lead">Doug’s focus on mental health began in 2010 after the suicide of a close family member. He went to counseling shortly
          thereafter to help process that loss and learn more about himself. Since then his studies have helped him achieve
          insight into his thought process and how it affects his emotions and behaviors. He has worked on addressing his
          core issues of insecurity, fear, frustration, and sadness. Processing his family history, as well as celebrating
          the things that bring him the most joy, has also helped him achieve a healthy emotional balance.</p>

        <p class="lead">Doug believes that the most important way one can steward their time and God-given abilities is by working toward
          quality mental health. He feels greatly rewarded by the growth and progress of those with whom he is fortunate
          enough to work.</p>

        <p class="lead">Doug is a strong advocate for life/work balance. He spends time with his wife, two children, friends and co-workers,
          and pursues continued growth in his passions, music and golf.</p>

      </div>
    </div>
  </div>
</div>






{% endblock %}

dbc/home/templates/home/forms.html
{% extends 'base.html' %}
        

  {% block content %}

       
<div id="forms">
<div class="padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-2"></div>
            <div class="col-lg-8">
            
                    <div class="card">
                            <div class="card-header text-center"> <h1 class="display-4">Forms</h1></div>
                            <div class="card-body text-center">
                              <p class="lead">In an effort to be the best steward of your time and financial resources, it is requested that you download and fill out the following 
                                  paperwork prior to your first appointment.  Doing so will allow you to get the most out of your first session and provide you with 
                                  insight into what will be discussedin that first session. Thank you in advance for taking a few moments to complete this step.
                              </p>
<br>
                              <a class="btn btn-primary btn-lg btn-block" href="https://drive.google.com/open?id=1RY1gsNjB8zfYry7NQE6lFdVhxEGS5iWM" role='button'>Informed Consent</a><br>
                              <a class="btn btn-primary btn-lg btn-block" href="https://drive.google.com/open?id=1kygT9-KQK9Zn9guJQt1rEt0aFUu4X0DA" role='button'>Intake</a><br>
                              <a class="btn btn-primary btn-lg btn-block" href="https://drive.google.com/open?id=1g7mHABqZ_BRjkz5mnIlQddEgMAWXm5YB" role='button'>Electronic Communication Consent</a><br>
                              <a class="btn btn-primary btn-lg btn-block" href="https://drive.google.com/open?id=1aUpX0VkW5CJ55le-s5reccWI1XyLLRPa" role='button'>Consent to Record</a><br>
                              <a class="btn btn-primary btn-lg btn-block" href="https://drive.google.com/open?id=1X9R5yvXEyYHjslim_UHQoo50C3FoocsG" role='button'>Supervisor Acknowledgement</a><br>
                              
                            </div>
                          </div> 
                </div>
            </div>
       

            <div class="col-lg-2"></div>
        </div>
    </div>
</div>
</div>
{% endblock %}

dbc/home/templates/home/index.html
 {% extends "base.html" %} {% block content %}
<div id="home">
  <div class="container"></div>
  <div class="padding">

    <div class="row text-center display-block">
      <div class="col-sm-6"></div>
      <div class="col-sm-5">
        <div class="card card-pic">
          <h1 class="ontop">Encourage Enrich Empower</h1>
          <br>
          <p class="ontop">Welcome to Doug Borrmann Christian Counseling. The mission of my practice is to Encourage you in the midst of your
            difficult seasons, to Enrich your life through education and customized strategies to achieve personal goals,
            and to Empower you with resources that will help you live each day to its maximum potential.
          </p>
          <br>
        </div>
      </div>
      <div class="col-sm-1"></div>
    </div>
  </div>
</div>
</div>
</div>

<div class="padding padding-home">
  <div class="container">
    <div class="row">
      <div class="card-deck text-center">
        <div class="card">
          <img class="card-img-top" src="/static/assets/adventure-backlit-clouds-772665.jpg" alt="Card image cap">
          <div class="card-body">
            <h4 class="card-title">-Encourage-</h4>
            <p class="lead">Isaiah 35:1-4 God’s word promises that the “wasteland will rejoice and blossom” and that “wilderness and desert
              will be glad” once again. We are called to “strengthen those who have tired hands and encourage those who have
              weak knees.” We all need regular doses of encouragement and I place a high value on having a listening ear
              and providing an encouraging message to those who are in troubled places.
            </p>

          </div>
        </div>
        <div class="card">
          <img class="card-img-top" src="/static/assets/bible-book-book-bindings-1112048.jpg" alt="Card image cap">
          <div class="card-body">
            <h4 class="card-title">-Enrich-</h4>
            <p class="lead">Proverbs 8:11 Wisdom is truly more valuable than gold. It comes in many forms and from many sources. I believe
              the path of self-exploration is a place where wisdom is gained. Learning about yourself is an amazing way to
              fine tune your strengths and discover what will work best for you in your effort to be your best self. I will
              help you walk along the path of self-exploration and provide insights along the way.
            </p>

          </div>
        </div>
        <div class="card">
          <img class="card-img-top" src="/static/assets/backlit-beach-christian-356642.jpg" alt="Card image cap">
          <div class="card-body">
            <h4 class="card-title">-Empower-</h4>
            <p class="lead">Ephesians 6:13-17 We are given by God many resources that provide us with strength when we need it most. The
              armor of God is a metaphor that informs us to live in truth, righteousness, peace, faith, salvation, and with
              the Spirit. I believe we all have personal expressions for these resources and it is my goal to help you realize
              them so that when the storms of life come you will be empowered and prepared.
            </p>

          </div>
        </div>
      </div>


    </div>
  </div>
</div>
</div>






{% endblock %}

dbc/home/templates/home/locations.html
{% extends "base.html" %}

{% block content %}

<div class="padding2">
    <div class="row">   
        <div class="jumbotron jumbotron-fluid">
    <div class="container">
      
      </div>
  </div>
</div>
</div>
<div class="container-fluid text-center">
    <h1 class="display-4">Two locations for your convenience</h1>
</div>

    
        
          <div class="padding2">
            <div class=container>

            

            <div class="card-deck">
                    <div class="card">
                            <div class="map-responsive">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5177.598048954005!2d-111.91477620117628!3d33.46769118630563!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x872b097b78f8aa15%3A0x548fed223791139!2s1717+N+77th+St+%2315%2C+Scottsdale%2C+AZ+85257!5e0!3m2!1sen!2sus!4v1531158253161" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
                      </div>
                            <div class="card-body">
                        <h5 class="card-title">Scottsdale Location</h5>
                        <p class="card-text">Parkview Office Building</p>
                        <p class="card-text">1717 N 77th St, Scottsdale, AZ 85257</p> 
                        <p>Suite 15</p>
                        <p>Available Monday and Saturday</p>
                      </div>
                    </div>
        
                    <div class="card">
                            <div class="map-responsive">
                              <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3323.6999307061647!2d-112.12443828529342!3d33.587139480734976!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x872b6c145299df2b%3A0xb38a71691c51655d!2s11024+N+28th+Dr%2C+Phoenix%2C+AZ+85029!5e0!3m2!1sen!2sus!4v1531334386365" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
                      </div>
                      <div class="card-body">
                            <h5 class="card-title">Phoenix Location</h5>
                            <p class="card-text">Lake Biltmore Corprate Center</p>
                            <p>11024 N 28th Dr. Phoenix, AZ 85257</p> 
                            <p>Suite 200</p>
                            <p>Available Friday</p>
                          </div>
                    </div>
                  </div>
                </div>
        
              </div>
    
    {% endblock content %}

dbc/home/templates/home/services.html
{% extends 'base.html' %} {% block content %}
<div id="serv">
  <div class="padding">
    <div class="container text-center">
      <div class="row">
        <div class="col"></div>
        <div class="col-sm-6 col-xs-12">
          <div class="card card-pic2">
            <div class="card-body">

              <h1 class="display-4">Services</h1>

              <p>Doug is passionate about working with anyone who desires to become their best self. He believes that emotional
                regulation is the keystone to that ambition. He is educated and trained in dealing with a variety of difficult
                but common issues and loves to share his insight in the effort to help others achieve their personal goals.
                He is competent in the treatment of:</p>
              <div class="row">
                <div class="col">

                  <p>Anxiety</p>
                  <p>Depression</p>
                  <p>Trauma</p>
                  <p>Coping Skills</p>
                  <p>Boundary Setting</p>
                  <p>Relationships</p>
                  <p>Cognitive Behavioral Therapy</p>
                </div>
                <div class="col">
                  <p>Addictions</p>
                  <p>Communication</p>
                  <p>Marital Issues</p>
                  <p>Grief Recovery</p>
                  <p>Emotional Health</p>
                  <p>Self-Esteem</p>
                  <p>Eye Movement Desensitization and Reprocessing</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

dbc/home/templates/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <div class="container container-nav text-center">
  <a class="navbar-brand" href="{%  url 'home:index' %}">
    
      <h2 class="h2-nav">Doug Borrmann</h2>
      <p class="lead lead-nav">Christian Counseling</p>
    
  </a>

  <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</div>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{%  url 'home:index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%  url 'home:about' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%  url 'home:services' %}">Services</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%  url 'home:forms' %}">Forms</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%  url 'home:locations' %}">Locations</a>
      </li>
    </ul>
  </div>
</nav>
       
<script>
    $(".nav .nav-link").on("click", function(){
      $(".nav").find(".active").removeClass(".active");
      $(this).addClass("active");
    });

    $(function () {
      $(document).scroll(function () {
        var $nav = $(".navbar-fixed-top");
        $nav.toggleClass('scrolled', $(this).scrollTop() > $nav.height());
      });
    });
</script>